name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      select_browser:
        description: "Seleccione el navegador"
        default: "chromium"
        required: true
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - Microsoft Edge
      
      insert_test: 
        description: "Ingrese el nombre del archivo"
        required: true
        type: string

  pull_request:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install allure playwright
      run: npm install -D allure-playwright

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test ${{ inputs.insert_test }} --project=${{ inputs.select_browser }}

    - name: Run allure report
      if: ${{ !cancelled() }}
      run:  allure generate --clean

    - name: Artifact to plawright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Artifact to allure report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
